//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSWDFinalProject.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAsset()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int UserAssetId { get; set; }
        public string AssetName { get; set; }
        public string UserId { get; set; }
        public string AssetPhoto { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> AssetYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
